// <auto-generated />
using System;
using DigiCoupon.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigiCoupon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DigiCouponContext))]
    [Migration("20260930125841_UpdateDashboardProcedure")]
    partial class UpdateDashboardProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigiCoupon.Domain.Entities.CouponRedemption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<int>("CustomerCouponId")
                        .HasColumnType("int")
                        .HasColumnName("customer_coupon_id");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_on");

                    b.Property<DateTime>("RedemptionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("redemption_date");

                    b.Property<int>("RestaurantBranchId")
                        .HasColumnType("int")
                        .HasColumnName("restaurant_branch_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_coupon_redemptions");

                    b.HasIndex("CustomerCouponId")
                        .HasDatabaseName("ix_coupon_redemptions_customer_coupon_id");

                    b.HasIndex("RestaurantBranchId")
                        .HasDatabaseName("ix_coupon_redemptions_restaurant_branch_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_coupon_redemptions_user_id");

                    b.ToTable("coupon_redemptions", (string)null);
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.CustomerCoupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouponNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("coupon_number");

                    b.Property<int>("CouponType")
                        .HasColumnType("int")
                        .HasColumnName("coupon_type");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit")
                        .HasColumnName("is_expired");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_on");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("RestaurantBranchId")
                        .HasColumnType("int")
                        .HasColumnName("restaurant_branch_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<int?>("TotalUsage")
                        .HasColumnType("int")
                        .HasColumnName("total_usage");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_customer_coupon");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_coupon_customer_id");

                    b.HasIndex("RestaurantBranchId")
                        .HasDatabaseName("ix_customer_coupon_restaurant_branch_id");

                    b.ToTable("customer_coupon", (string)null);
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("MemberCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("member_code");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mobile");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_on");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nick_name");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("public_token");

                    b.Property<int?>("RestaurantBranchId")
                        .HasColumnType("int")
                        .HasColumnName("restaurant_branch_id");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int")
                        .HasColumnName("restaurant_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("RestaurantBranchId")
                        .HasDatabaseName("ix_customers_restaurant_branch_id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_customers_restaurant_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<int>("CustomerCouponId")
                        .HasColumnType("int")
                        .HasColumnName("customer_coupon_id");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_on");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("int")
                        .HasColumnName("payment_mode");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receipt_number");

                    b.Property<int>("RestaurantBranchId")
                        .HasColumnType("int")
                        .HasColumnName("restaurant_branch_id");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transaction_reference");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("CustomerCouponId")
                        .HasDatabaseName("ix_payments_customer_coupon_id");

                    b.HasIndex("RestaurantBranchId")
                        .HasDatabaseName("ix_payments_restaurant_branch_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payments_user_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FssaiLicenseNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fssai_license_no");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mobile");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_restaurants_user_id");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.RestaurantBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("branch_name");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mobile");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_on");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pincode");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_restaurant_branches");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_restaurant_branches_restaurant_id");

                    b.ToTable("restaurant_branches", (string)null);
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mobile");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.CouponRedemption", b =>
                {
                    b.HasOne("DigiCoupon.Domain.Entities.CustomerCoupon", "CustomerCoupon")
                        .WithMany("Redemptions")
                        .HasForeignKey("CustomerCouponId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_redemptions_customer_coupon_customer_coupon_id");

                    b.HasOne("DigiCoupon.Domain.Entities.RestaurantBranch", "RestaurantBranch")
                        .WithMany("CouponRedemptions")
                        .HasForeignKey("RestaurantBranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_redemptions_restaurant_branches_restaurant_branch_id");

                    b.HasOne("DigiCoupon.Domain.Entities.Users", "User")
                        .WithMany("CouponRedemption")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_coupon_redemptions_users_user_id");

                    b.Navigation("CustomerCoupon");

                    b.Navigation("RestaurantBranch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.CustomerCoupon", b =>
                {
                    b.HasOne("DigiCoupon.Domain.Entities.Customers", "Customer")
                        .WithMany("Coupon")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_customer_coupon_customers_customer_id");

                    b.HasOne("DigiCoupon.Domain.Entities.RestaurantBranch", "RestaurantBranch")
                        .WithMany("CustomerCoupon")
                        .HasForeignKey("RestaurantBranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_customer_coupon_restaurant_branches_restaurant_branch_id");

                    b.Navigation("Customer");

                    b.Navigation("RestaurantBranch");
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.Customers", b =>
                {
                    b.HasOne("DigiCoupon.Domain.Entities.RestaurantBranch", "RestaurantBranch")
                        .WithMany("Customers")
                        .HasForeignKey("RestaurantBranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_customers_restaurant_branches_restaurant_branch_id");

                    b.HasOne("DigiCoupon.Domain.Entities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_customers_restaurants_restaurant_id");

                    b.Navigation("Restaurant");

                    b.Navigation("RestaurantBranch");
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.Payment", b =>
                {
                    b.HasOne("DigiCoupon.Domain.Entities.CustomerCoupon", "CustomerCoupon")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerCouponId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_payments_customer_coupon_customer_coupon_id");

                    b.HasOne("DigiCoupon.Domain.Entities.RestaurantBranch", "RestaurantBranch")
                        .WithMany("Payments")
                        .HasForeignKey("RestaurantBranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_payments_restaurant_branches_restaurant_branch_id");

                    b.HasOne("DigiCoupon.Domain.Entities.Users", "User")
                        .WithMany("Payment")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_payments_users_user_id");

                    b.Navigation("CustomerCoupon");

                    b.Navigation("RestaurantBranch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.Restaurant", b =>
                {
                    b.HasOne("DigiCoupon.Domain.Entities.Users", "User")
                        .WithMany("Restaurants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_restaurants_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.RestaurantBranch", b =>
                {
                    b.HasOne("DigiCoupon.Domain.Entities.Restaurant", "Restaurant")
                        .WithMany("Branches")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_branches_restaurants_restaurant_id");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.CustomerCoupon", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.Customers", b =>
                {
                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.Restaurant", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.RestaurantBranch", b =>
                {
                    b.Navigation("CouponRedemptions");

                    b.Navigation("CustomerCoupon");

                    b.Navigation("Customers");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DigiCoupon.Domain.Entities.Users", b =>
                {
                    b.Navigation("CouponRedemption");

                    b.Navigation("Payment");

                    b.Navigation("Restaurants");
                });
#pragma warning restore 612, 618
        }
    }
}
