@DigiCoupon.Server_HostAddress = https://localhost:7181/api
@DigiCoupon.Register = /auth/register
@DigiCoupon.Login = /auth/login
@DigiCoupon.Restuarant = /restuarant
@DigiCoupon.Dashboard = /home
@DigiCoupon.Branch = /restuarant/branch
@DigiCoupon.AllBranch = /restuarant/all_branch
@DigiCoupon.Customers = /customer
@DigiCoupon.CustomerCoupon = /customercoupon
@DigiCoupon.CouponRedemption = /CouponRedemption
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSmF0aW4gSm9zaGkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJqYXRpbkBnbWFpbC5jb20iLCJleHAiOjE3OTA3NzM5MDQsImlzcyI6IkFNU0JhY2tlbmQiLCJhdWQiOiJBTVNGcm9udGVuZCJ9.MdHmx3KZsGdM40kIId2JRL8pMqQAa1TG_oderGbHxZw

### dashboard get
get {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Dashboard}}/9/2026-09-25
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}

### register request
POST {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Register}}
Accept: application/json
Content-Type: application/json
{
  "Name":"User One",
  "Email":"user_one@gmail.com",
  "Mobile":"1111111111",
  "Password":"11111111"
}

###  login request
POST {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Login}}
Accept:application/json
Content-Type:application/json
{
  "UserName":"1111111111",
  "Password":"11111111"
}

### restuarant post request 
POST {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Restuarant}}
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}
{
  "Id":0,
  "Name":"Restuarant A",
  "Email":"restuarant_a@gmail.com",
  "Mobile":"1111111111",
  "FssaiLicenseNo":"FSSAI001",
  "Address":"Rajkot"
}

### second restuarant post
POST {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Restuarant}}
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}
{
  "Id":0,
  "Name":"Restuarant D",
  "Email":"restuarant_D@gmail.com",
  "Mobile":"4444444444",
  "FssaiLicenseNo":"FSSAI004",
  "Address":"Ahmedabad"
}

### second restuarant put
PUT {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Restuarant}}/11
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}
{
  "Id":11,
  "Name":"Restuarant C Edit",
  "Email":"restuarant_c@gmail.comEdit",
  "Mobile":"3333333333EDIT",
  "FssaiLicenseNo":"FSSAI003EDIT",
  "Address":"Ahmedabad EDIT"
}

### RESTUARANT delete
delete {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Restuarant}}/11
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}

### RESTUARANT get
get {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Restuarant}}/10
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}


### RESTUARANT branch post
POST {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Branch}}
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}
{
  "Id":"0",
  "RestaurantId":10,
  "BranchName":"Branch A",
  "Address":"adddress A",
  "City":"Rajkot",
  "State":"Gujarat",
  "Pincode":"360002",
  "Mobile":"7572899703",
  "Email":"branch_b@gmail.com"
}

### RESTUARANT branch put
put {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Branch}}/6
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}
{
  "Id":"6",
  "RestaurantId":9,
  "BranchName":"madhapar branch edit",
  "Address":"raiya edit",
  "City":"Rajkot edit",
  "State":"Gujarat edit",
  "Pincode":"360000000",
  "Mobile":"3333333333",
  "Email":"branch_3@gmail.com"
}

### RESTUARANT branch put
delete {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Branch}}/6
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}


### RESTUARANT branch Get all
get {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.AllBranch}}/9
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}

### RESTUARANT branch Get 
get {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Branch}}/5
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}

### CUSTOMER post
POST {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Customers}}
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}
{
  "Id":0,
  "RestaurantId":10,
  "RestaurantBranchId":7,
   "FirstName":"Customer",
   "LastName" :"B1",
   "NickName":"Customer B2",
   "Mobile":"2223336669",
   "MemberCode":"R9-003",
   "PublicToken":"url"
}

### CUSTOMER post 1
POST {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Customers}}
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}
{
  "Id":0,
  "RestaurantId":9,
  "RestaurantBranchId":4,
   "FirstName":"Customer",
   "LastName" :"A2",
   "NickName":"Customer A2",
   "Mobile":"2222222222",
   "MemberCode":"R9-002",
   "PublicToken":"url"
}

### CUSTOMER put 2
put {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Customers}}/6
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}
{
  "Id":6,
  "RestaurantId":9,
  "RestaurantBranchId":5,
  "FirstName":"Customer",
  "LastName" :"A4",
  "NickName":"Customer",
  "Mobile":"4444444444",
  "MemberCode":"R9-04",
  "PublicToken":"url"
}

### CUSTOMER delete 2
delete {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Customers}}/4
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}

### CUSTOMER get by id 3
get {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Customers}}/3
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}

### CUSTOMER get by restuarant id 9
get {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.Customers}}/all/9
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}

### CUSTOMER Coupon post 1
POST {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.CustomerCoupon}}
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}
{
  "Id":0,
  "RestaurantBranchId":7,
  "CustomerId":10,
  "CouponNumber":"DC",
  "CouponType":2,
  "Price":2400.00,
  "StartDate":"2026-09-01",
  "EndDate":"2026-09-30",
  "TotalUsage":0
}

### CUSTOMER Coupon put 1
put {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.CustomerCoupon}}/1
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}
{
  "Id":1,
  "RestaurantBranchId":4,
  "CustomerId":9,
  "CouponNumber":"DC",
  "CouponType":2,
  "Price":3000.00,
  "StartDate":"2026-09-01",
  "EndDate":"2026-09-30",
  "TotalUsage":0
}

### CUSTOMER Coupon delete 1
delete {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.CustomerCoupon}}/2
Accept: application/json
Content-Type: application/json

### CUSTOMER Coupon get by customer 1
get {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.CustomerCoupon}}/all/4
Accept: application/json
Content-Type: application/json

### Coupon redemption delete by coustomer coupon
delete {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.CouponRedemption}}/all/1
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}


### Coupon redemption post 1
POST {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.CouponRedemption}}
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}
{
  "Id":0,
  "RestaurantBranchId":7,
  "CustomerCouponId":4,
  "RedemptionDate":"2026-09-26"
}

### COUPON REDEMPTION get by coupon id
get {{DigiCoupon.Server_HostAddress}}{{DigiCoupon.CouponRedemption}}/all/1
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{Token}}